apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd
    
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd
    spec:
      containers:
        - image: httpd:2.4-alpine
          name: http